#Setting the logging levels for the service
logging:
  level:
    com.netflix: DEBUG
    org.springframework.web: WARN
    com.gfi.microservicios: DEBUG

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
        defaultZone: http://localhost:8761/eureka/

server:
  contextPath:   /auth

   #Distributed tracing
spring:
   zipkin:
      baseUrl: http://localhost:9411